version: '3.7'

networks:
  videoWebSite:
    driver: bridge

services:
  mysql:
    container_name: db
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=88888888
      - MYSQL_DATABASE=videowebsite
      - TZ=Asia/Shanghai
    ports:
      - "3306:3306"
    networks:
      - videoWebSite

  redis:
    container_name: redis
    image: redis:latest
    restart: on-failure
    volumes:
      - /usr/local/redis:/usr/local/redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass 88888888
    networks:
      - videoWebSite

  elasticsearch:
    image: elasticsearch:8.9.0
    container_name: es
    environment:
      - cluster.name=elasticsearch #设置集群名称为elasticsearch
      - discovery.type=single-node #以单一节点模式启动
      - ES_JAVA_OPTS=-Xms256m -Xmx1024m #设置使用jvm内存大小
      - ELASTIC_PASSWORD=88888888-elasticsearch   #密码
      - xpack.security.enabled=true
    volumes:
      - /usr/local/elasticsearch/data:/usr/local/elasticsearch/data
      - ./repository/es/plugins/ik:/usr/share/elasticsearch/plugins/ik
    ports:
      - "9200:9200"
    restart: always
    networks:
      - videoWebSite

#  kibana:
#    image: kibana:8.9.0
#    container_name: kibana
#    environment:
#      - elasticsearch.hosts=http://es:9200 #设置访问elasticsearch的地址
#      - ELASTICSEARCH_USERNAME=kibana_system
#      - ELASTICSEARCH_PASSWORD=88888888  #elastic密码
#      - I18N_LOCALE=zh-CN          #中文
#    ports:
#      - "5601:5601"
#    depends_on:
#      - elasticsearch
#    networks:
  #    - videoWebSite

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=mutezebra
      - RABBITMQ_DEFAULT_PASS=88888888
    ports:
      - "5672:5672"
    restart: always
    networks:
      - videoWebSite

  web:
    build: .
    container_name: web
    depends_on:
      - mysql
      - redis
    volumes:
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    restart: always
    networks:
      - videoWebSite